on: [push, pull_request]

name: cover

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.BRISK }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: |
          out <- covr::package_coverage()
          print(out)
          perc <- covr::percent_coverage(out)
          if (perc < 100) stop("Some lines not covered by tests.")
        shell: Rscript {0}
